# Generated by Django 3.0a1 on 2019-09-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of message.', max_length=120)),
                ('message', models.TextField(help_text='Whats on your mind, hmm....')),
            ],
        ),
    ]
